### ISSUE TITLE
Recipient defined with id is not found within message info during data decryption.

### ISSUE THREAD

**Issue by unktomi** [VirgilSecurity/virgil-e3kit-js#107]
Getting this error. What am i doing wrong?

**Comment by unktomi** [comment]
This is occurring in decryptFile. However the same code calling decrypt on a buffer works as expected.

**Comment by snanovskyi** [comment]
Hi @unktomi 👋

This error means that you messed up with keys somewhere in your application. You need to provide public key of recipient/sender to encryptFile/decryptFile methods respectively.

Also a simple code snippet or demo that reproduces the problem will help if you're sure that everything is right.

PS: Does this error occur in this example - https://github.com/VirgilSecurity/virgil-e3kit-js/blob/master/examples/encryptFile.html ? It's quite outdated and I'm going to update it later today.

**Comment by unktomi** [comment]
Thanks. I figured it out. I was passing the wrong public key. my bad.

**Comment by snanovskyi** [comment]
👍
