### ISSUE TITLE
npm install version 2.2.1 broken

### ISSUE THREAD

**Issue by camhart** [VirgilSecurity/virgil-e3kit-js#109]
**Describe the bug**
`npm i @virgilsecurity/e3kit-browser` doesn't work

**To Reproduce**
`npm i @virgilsecurity/e3kit-browser`

Output:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @virgilsecurity/e3kit-base@^2.2.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@virgilsecurity/e3kit-browser'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cam\AppData\Roaming\npm-cache\_logs\2020-05-07T21_48_26_683Z-debug.log
```

**Expected behavior**
Should install latest version

**Desktop (please complete the following information):**
 - OS: windows 10 64 bit, npm version 6.13.7

**Comment by camhart** [comment]
I should add, it works if you do `npm i @virgilsecurity/e3kit-browser@2.2.0`

**Comment by xlwknx** [comment]
Hi, @camhart !
Thank you contacting us, problem was fixed.
Please try to install `@virgilsecurity/e3kit-browser@2.2.1`
