### ISSUE TITLE
Unit test fail due to missing declaration file

### ISSUE THREAD

**Issue by orthodoc** [VirgilSecurity/virgil-e3kit-js#113]
**Describe the bug**
When running unit tests, the app fails to build (test build) with the following error:
`ERROR in node_modules/@virgilsecurity/e3kit-base/dist/types/GroupLocalStorage.d.ts:1:22 - error TS6053: File '/Users/bdb/projects/binder/node_modules/@virgilsecurity/e3kit-base/declarations.d.ts' not found.`
 

**To Reproduce**
1. Install with `npm i -S @virgilsecurity/e3kit-browser`
2. Add the following to `angular.json`:
```json
{
  "glob": "{libfoundation,libpythia}.browser.wasm",
  "input": "node_modules/@virgilsecurity/e3kit-browser/dist",
   "output": "."
}
```
3. Run `npm run test`

**Expected behavior**
I expect the build process to continue and the test suite to complete. I downloaded the examples folder and saw that the tests are catching an error that's different than this. Ii also noticed that the `angular.json` entry is referring to a package outside the ionic example folder.

**Desktop (please complete the following information):**
 - OS: Mac]
 - Browser Chrome
 - Version 2.3.0

**Additional context**
Commenting out the reference to the `declarations.d.ts` file in the `GroupLocalStorage.d.ts` makes the test suite complain about the missing `*.browser.wasm` files.
`ionic build` and `ionic serve` run fine, though

Edit: subsequently I discovered that `ionic build` and `ionic serve` fail due to the same error

**Comment by orthodoc** [comment]
Thanks for adding the declaration file. Got to check this out.

**Comment by xlwknx** [comment]
Hello, @orthodoc !
Sorry for a late response, the declaration file is fixed in [v2.3.1](https://www.npmjs.com/package/@virgilsecurity/e3kit-browser/v/2.3.1)
I wasn't able to reproduce this problem, so please report how it works for you!

**Comment by orthodoc** [comment]
@xlwknx unfortunately the build process fails with this error:
```shell
ERROR in ./node_modules/@virgilsecurity/e3kit-browser/browser.es.js 11:81-95
"export 'default' (imported as 'foundationWasm') was not found in './dist/libfoundation.browser.wasm'
```
Though `angular.json` is configured this way
```json
{
  "glob": "{libfoundation,libpythia}.browser.wasm",
  "input": "node_modules/@virgilsecurity/e3kit-browser/dist",
   "output": "."
}
```
the build process seems to be happening before the required assets are copied to the build folder. My destination folder is a sub folder. I don't know if this is impacting the copy process.

**Comment by xlwknx** [comment]
@orthodoc how you import the  EThree instance? 
EThree for Ionic should be imported also from `dist` folder:
``` 
import { EThree } from '@virgilsecurity/e3kit-browser/dist/browser.es';
```
This is not documented yet, but we working example here:
https://github.com/VirgilSecurity/virgil-e3kit-js/tree/master/examples/ionic

**Comment by orthodoc** [comment]
This may have been the issue. Let me give it another try.

**Comment by orthodoc** [comment]
The backend function is a callable function, while the ionic example in this repo makes an api call to the firebase function for generating virgil jwt.
`ionic build` fails to build as a result even though i have a callable function and the appropriate code on the front end to make that call.
So in the end, I am not able to implement e2e.

**Comment by xlwknx** [comment]
Hi @orthodoc 
I don't quite understand the problem, could you please send an error log of `ionic build` command?

**Comment by orthodoc** [comment]
I was working on a separate branch, so the delay. 

I have integrated the encrypt service and pushed to the `encrypt` branch of this repo: [Binder](https://github.com/orthodoc/binder).

It's a long output. I have a separate firebase/functions folder that should not be part of the build process. I checked `angular.json` in this regard, and found nothing of that sort. But the error output primarily relates to packages in the firebase/functions folder.

The `dev` branch has the exact same configuration and all the tests/specs run fine.

Hope this explains it better.

**Comment by himalayaahuja** [comment]
> @orthodoc how you import the EThree instance?
> EThree for Ionic should be imported also from `dist` folder:
> 
> ```
> import { EThree } from '@virgilsecurity/e3kit-browser/dist/browser.es';
> ```
> 
> This is not documented yet, but we working example here:
> https://github.com/VirgilSecurity/virgil-e3kit-js/tree/master/examples/ionic

Hi @xlwknx unfortunately the ioni example in the above link isn't working anymore and is throwing same errors of `libfoundation.browser.wasm 404 (Not Found)` etc
