### ISSUE TITLE
IsInvalidPath buggy on Windows

### ISSUE THREAD

**Issue by camhart** [VirgilSecurity/virgil-e3kit-js#117]
**Describe the bug**
IsInvalidPath returns true forwindows paths when they start with `{driveLetter}:`.  

**To Reproduce**
Try running  `e3kit.EThree.initialize` on Windows with a custom absolute path value as dir path for KeyEntryStorage it'll throw TypeError `'groupStorageName' is not a valid path`.  This is due to IsInvalidPath not handling {DriveLetter}: (ie, C:)--see https://github.com/jonschlinkert/is-invalid-path/issues/4.  It returns true for any path with a colon in it.

```
await e3kit.EThree.initialize(
      tokenCallback(ds),
      {
        foundationWasmPath: path.join(wasmBasePath, 'libfoundation.wasm'),
        pythiaWasmPath: path.join(wasmBasePath, 'libpythia.wasm'),
        keyEntryStorage: new KeyEntryStorage({
          dir: dirPath //passing anything here, and the default value throws on windows
        }),
        groupStorageName: groupStorageDir
      }
    )
```

**Expected behavior**
`C:\something` is a valid path on Windows.

**Desktop (please complete the following information):**
 - OS: Windows 10, electron 8.3

**Comment by xlwknx** [comment]
Hello again, @camhart !
I'm fixed this, package already published on npm with v2.3.2 version, please check it out.
Check with `is-invalid-path` was useless, because `mkdirp`can throw errors by itself.
