### ISSUE TITLE
No way to close levelup instance

### ISSUE THREAD

**Issue by camhart** [VirgilSecurity/virgil-e3kit-js#131]
There's no way to close the levelup database.  I have a situation where multiple instances of my application can be ran at once.  I'm having to hack in support for closing the levelup database.

**Comment by dkosolap** [comment]
Hi @camhart!
I suppose we talk about e3kit-node?
Method `initialize` of e3kit instance has [groupStorageName](https://virgilsecurity.github.io/virgil-e3kit-js/e3kit-native/interfaces/ethreenativeinitializeoptions.html#groupstoragename) optional.
Try to add to instance specific name, it's could you help.
Here is an [example](https://github.com/VirgilSecurity/virgil-e3kit-js/blob/master/examples/node/index.js#L37-L40).

**Comment by camhart** [comment]
How would I then close the level up instance?

**Comment by dkosolap** [comment]
At this moment we don't have such functionality, but in the nearest future we are going to add it.
I will let you know when it's ready.

**Comment by azirb** [comment]
Closing as outdated
