### ISSUE TITLE
Error: Have the issue when import EThree

### ISSUE THREAD

**Issue by HN00** [VirgilSecurity/virgil-e3kit-js#134]
**Describe the bug**
I import EThree from '@virgilsecurity/e3kit-browser' and have the error when run on web.

**Screenshots**
![image](https://user-images.githubusercontent.com/49835271/101607478-3d3dba80-3a37-11eb-8c86-76d4acfa20a1.png)

**Comment by HN00** [comment]
<img width="1315" alt="Screen Shot 2020-12-10 at 13 01 07" src="https://user-images.githubusercontent.com/49835271/101727805-c7ddf280-3ae7-11eb-9e6f-c5608f8a89cf.png">
And I have the error when use "derivePassword" method.

**Comment by mbalyaba** [comment]
Hi HN00,
Does it actual ?
