### ISSUE TITLE
Group Encryption: KeyknoxClientError while trying to add a member to a Group.

### ISSUE THREAD

**Issue by arun-prasad-r** [VirgilSecurity/virgil-e3kit-js#136]
**Describe the bug**
I'm using e3kit js sdk. "@virgilsecurity/e3kit-browser": "^2.4.0",
I'm trying to  add an additional member to an existing group following the instructions in the documentation. 
I am getting the following 400 error: 
```
{"code":50021,"message":"`identities` parameter is not set"}
```

**To Reproduce**
``` 
// create a group

const groupId = 'unique_group_id';
const groupIntiatorId = 'application_user_id'
const participants = await eThree.findUsers([groupIntiatorId]);
const group = await eThree.createGroup(groupId, participants);
```
^^ The group gets created successfully. 

```
// load the existing group and try adding an existing eThree user.

const group = await eThree.loadGroup(groupId, groupInitiatorCard); //able to load group
const existingParticipant = await eThree.findUsers(memberId); //able to load existingParticipant Card
await group.add(newParticipant); // <- Errors here.  KeyknoxClientError: `identities` parameter is not set

// I am getting the following 400 error: 

{"code":50021,"message":"`identities` parameter is not set"}
```

**Expected behavior**
Member should be added to the group.

**Screenshots**
<img width="358" alt="Screenshot 2020-12-16 at 2 25 04 AM" src="https://user-images.githubusercontent.com/41289997/102271876-f0ca1180-3f45-11eb-8fa7-992869c944a1.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by mbalyaba** [comment]
Hi Arun Prasad,
Thanks for the detailed issue description.
We will try to reproduce and reply as soon as possible.

**Comment by mbalyaba** [comment]
Hi Arun Prasad,
We have tried to reproduce the issue, but without success.
All works as expected.
Please, could you provide more details about your sample code ? (maybe some complete test code block)

**Comment by abhigyan2311** [comment]
@mbalyaba : I am also facing this issue with nodejs SDK.

**CODE:**
![image](https://user-images.githubusercontent.com/5149209/123060005-f722d400-d427-11eb-8b53-9dede6d02258.png)

**ERROR:**
![image](https://user-images.githubusercontent.com/5149209/123060065-073ab380-d428-11eb-823f-61824f505e54.png)
