### ISSUE TITLE
Upgrade of axios and ini libraries needed to resolve vulnerabilities

### ISSUE THREAD

**Issue by jeremyljohnson** [VirgilSecurity/virgil-e3kit-js#137]
**Describe the bug**
When installing the latest version of virgil-e3kit-js via npm, we see 2 vulnerabilities that require manual review.  Hopefully updating the version of axios to >=0.21.1 and ini to >1.3.6 will resolve the issue as per npm's output. Instead, we see vulnerability warnings for @virgilsecurity/keyknox and virgil-pythia:

 Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Server-Side Request Forgery                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ axios                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.21.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @virgilsecurity/e3kit-browser                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @virgilsecurity/e3kit-browser > @virgilsecurity/e3kit-base > │
│               │ @virgilsecurity/keyknox > axios                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1594                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Server-Side Request Forgery                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ axios                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.21.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @virgilsecurity/e3kit-browser                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @virgilsecurity/e3kit-browser > @virgilsecurity/e3kit-base > │
│               │ virgil-pythia > axios                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1594                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

**To Reproduce**
npm install @virgilsecurity/e3kit-browser@latest

**Expected behavior**
installation of package without warnings

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - npm v14.16.0 
- e3kit-browser version 2.4.1

Thanks for the help on this one!

**Comment by mbalyaba** [comment]
Hi @jeremyljohnson ,
We have published updated version 2.4.2.

**Comment by mbalyaba** [comment]
Fixed version 2.4.2
