### ISSUE TITLE
KeynoxClient Error on adding group participant

### ISSUE THREAD

**Issue by abhigyan2311** [VirgilSecurity/virgil-e3kit-js#143]
I am facing this issue with nodejs SDK.

**CODE:**
![image](https://user-images.githubusercontent.com/5149209/123060005-f722d400-d427-11eb-8b53-9dede6d02258.png)

**ERROR:**
![image](https://user-images.githubusercontent.com/5149209/123060065-073ab380-d428-11eb-823f-61824f505e54.png)

_Originally posted by @abhigyan2311 in https://github.com/VirgilSecurity/virgil-e3kit-js/issues/136#issuecomment-866624449_

**Comment by abhigyan2311** [comment]
Ok I found what the issue is, if you try to add a participant which is already there in the group then that error is thrown.
Can we please have a more graceful error message/handling for that?

**Comment by mbalyaba** [comment]
Hi @abhigyan2311 ,
Thanks for the provided information.
We will try to add more graceful error message/handling for that case.

**Comment by mbalyaba** [comment]
Fixed in version 2.4.5
