### ISSUE TITLE
Does not work with Vite

### ISSUE THREAD

**Issue by x8BitRain** [VirgilSecurity/virgil-e3kit-js#154]
**Describe the bug**
Loading any of the `e3kit-browser` packages, including via <script> tag results in errors. Using version 2.5.2 `"@virgilsecurity/e3kit-browser": "^2.5.2",`

When importing normally with `import { EThree } from '@virgilsecurity/e3kit-browser` I get:

`Failed to resolve import "env" from "../../node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm". Does the file exist?`

When importing with `import { EThree } from '@virgilsecurity/e3kit-browser/dist/browser.asmjs.es'` I get:

`browser.asmjs.es.js?v=3b600961:12632 Uncaught TypeError: Cannot set properties of undefined (setting 'Stream')`

**To Reproduce**
1. Install e3kit and vite-plugin-wasm
2. add `optimizeDeps: {
    exclude: ['@virgilsecurity/e3kit-browser'],
  }` and `plugins: [
    wasm(), ]` to vite config
3. import e3kit via either `import { EThree } from '@virgilsecurity/e3kit-browser'` or `'@virgilsecurity/e3kit-browser/dist/browser.asmjs.es'`
4. See error when starting vite project in browser

**Expected behavior**
Should be able to use E3Kit normally and initialize it but the app does not build past this import step.

**Screenshots**
when importing via `@virgilsecurity/e3kit-browser/dist/browser.asmjs.es`:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/15372551/215265162-70d0a96a-141a-4e7d-af6e-e745b9531563.png">

when importing normally `@virgilsecurity/e3kit-browser`

<img width="923" alt="image" src="https://user-images.githubusercontent.com/15372551/215265188-a682d1c1-44e6-4916-b616-1441849b4565.png">

The same 

**Desktop (please complete the following information):**
 - OS: Macos M1 max
 - Browser Chrome 110
 - Version 110

**Additional context**
The same `Cannot set properties of undefined (setting 'Stream')` error occurs when loading the lib with UMD via script tag.

Thanks for any help!

**Comment by azirb** [comment]
Hello! @x8BitRain, know about browser.umd.js import, trying to fix this error! 
When you download e3kit-browser via npm, you do not need <script> tag. And use `await Ethree.initialize` to normally import .wasm file.

**Comment by x8BitRain** [comment]
Thanks for looking into it! 

When I use the script tag alone, without the import/npm package, the same issue happens.

`Cannot set properties of undefined (setting 'Stream')`

This is a blank html page with the browser.umd.js using the script tag, a similar error happens on all browsers: https://codepen.io/BitRain/full/KKBejLX
same with `browser.asmjs.umd.js`

**Comment by azirb** [comment]
Yep, trying to fix this error. Working on it right now !

**Comment by azirb** [comment]
Hello again @x8BitRain ! Fix this error in 2.5.4 version! Try it now and give some feedback! Thanks for reporting!

**Comment by azirb** [comment]
Closing the ticket as fixed. Please create a new one if there are any more issues

**Comment by x8BitRain** [comment]
Hi, thanks for fixing this! It works via script tag now, but unfortunately the issue persists with Vite and import via NPM.
I will continue to use it via script tag for the moment but it would be nice to have it bundled with Vite!

<img width="937" alt="image" src="https://user-images.githubusercontent.com/15372551/216982308-9ba15292-c62f-4388-9ba4-0230bbc51502.png">
