### ISSUE TITLE
TypeError: Cannot set property 'Stream' of undefined

### ISSUE THREAD

**Issue by gz1992** [VirgilSecurity/virgil-e3kit-js#157]
**Describe the bug**
Hey guys, i've been trying to use virgil on my new react native (0.70.6) project. The problem is that this react native version uses gradle 7. And this project depends on react-native-virgil-cripto , that uses gradle 3 and didnt updated since then. I tryed to update directly on virgil-cripto build.gradle 3 changes to run the project [(here are the changes)](https://github.com/VirgilSecurity/react-native-virgil-crypto/issues/71#issuecomment-1411425030) .. but then i get the title error: **TypeError: Cannot set property 'Stream' of undefined**

**To Reproduce**
1. create a new react native project and Install all libraries necessary, for virgil-e3kit-js 
2. try to build the app
3. not working, access the react-native-virgil-cripto build.gradle and make the changes written [here](https://github.com/VirgilSecurity/react-native-virgil-crypto/issues/71#issuecomment-1411425030)
4. run the app and try to initialize your Ethree through the command 
![image](https://user-images.githubusercontent.com/3978892/216061893-74c462a2-1169-4905-8ecf-ddca7f50e1e6.png)

**Expected behavior**
It should initialize without a problem

**Screenshots**
![image](https://user-images.githubusercontent.com/3978892/216061997-2fb0eae9-93a7-47a4-8bf6-517ad1f32eeb.png)

**Desktop (please complete the following information):**
 - OS: Android 12

**Smartphone (please complete the following information):**
 - Pixel 2

My libraries used:
![image](https://user-images.githubusercontent.com/3978892/216062808-982f360e-6897-4c1b-93c8-8fa118e26d23.png)

**Comment by YASHRAJ-ANAND** [comment]
Same issue here

**Comment by azirb** [comment]
Hello @gz1992 @YASHRAJ-ANAND, watching on it! Thanks for report !

**Comment by gz1992** [comment]
NICE!!! My first tests worked, i am going to check it better later!!!

**Comment by gz1992** [comment]
@rstp-god , thanks, i can't reproduce this error!!
I have another one that i am not sure if it is related #159

**Comment by rstp-god** [comment]
Closed as resolved!
