### ISSUE TITLE
Could not find a declaration file for module '@virgilsecurity/e3kit-browser' when upgrading from 2.5.1 to 2.5.4

### ISSUE THREAD

**Issue by thecannabisapp** [VirgilSecurity/virgil-e3kit-js#162]
**Describe the bug**
I'm trying to upgrade from 2.5.1 of `@virgilsecurity/e3kit-browser` to 2.5.4. But after I upgraded, typescript gave me errors on missing declaration files.

<img width="690" alt="Screenshot 2023-05-31 at 10 21 35" src="https://github.com/VirgilSecurity/virgil-e3kit-js/assets/58605231/aa2e9677-5bdc-48dc-ba94-a348b864e893">

I've tried changing my import from `import { Data, EThree, type SdkError } from "@virgilsecurity/e3kit-browser";` to `import { Data, EThree, type SdkError } from "@virgilsecurity/e3kit-browser/dist";` but it only removes the error in vs code but doesn't work during the build.

<img width="889" alt="Screenshot 2023-05-31 at 10 23 02" src="https://github.com/VirgilSecurity/virgil-e3kit-js/assets/58605231/8d022f9c-816f-48d5-9921-30358587c4ce">

**To Reproduce**
Steps to reproduce the behaviour:
1. Upgrade from version 2.5.1 to 2.5.4
2. `import { Data, EThree, type SdkError } from "@virgilsecurity/e3kit-browser`
3. See the error

**Expected behavior**
No TS errors on missing declaration files.

**Comment by rstp-god** [comment]
Hello @chinesehemp !I do not change tsconfig file for this version, will check this! Ty for report!

**Comment by rstp-god** [comment]
@chinesehemp Hello! Release 2.5.5 version, back to classic dirs, all types now in ./dist/types like in 2.5.1 check now!
