### ISSUE TITLE
Trying to implement e3kit on Expo but getting this error on EThree.initialize [TypeError: `renewJwtFn` must be a function]

### ISSUE THREAD

**Issue by yiytan92** [VirgilSecurity/virgil-e3kit-js#17]
Could someone explain this error? Occuring on this line:
const eThreePromise = yield api('virgil-jwt', 'GET', authToken, {
        }).then(virgilResponse => {
            console.log('virgilREsponse :', virgilResponse)
            console.log("GOT VIRGIL JWT")
            return EThree.initialize(Promise.resolve(virgilResponse.virgilToken), { keyEntryStorage })
        }).catch((error) => {
            console.log('E3 error :', error)
        })

**Comment by xlwknx** [comment]
@yiytan92 
So where the error, or error log maybe?

**Comment by xlwknx** [comment]
Oh I see, it in the title.
And I see you got response here: https://github.com/VirgilSecurity/virgil-sdk-javascript/issues/46 and didn't implement it.

**Comment by yiytan92** [comment]
I managed to fix it. I npm installed buffer and included it as a global variable.
If i'm getting this, i assume it's a good sign
IdentityAlreadyExistsError: This identity is already registered on Virgil Cloud. To load private key use EThree.restorePrivateKey or EThree.rotatePrivateKey

**Comment by yiytan92** [comment]
I have a question, if we handle eThree initialization in our authentication flow, but I want to call the encryption functions as well as the look up public key functions in a different component (such as in chatrooms), I couldn't find any examples of the eThree object being passed down to different components. I tried it myself but I couldn't achieve it. Basically, is there a way to call eThree functions after eThree initialized in a different page?

**Comment by xlwknx** [comment]
1. IdentityAlreadyExistsError. Register method should call only once after user is registered. After you call register method, you create private key with user identity and it is taken. Like if you register email and cannot register another email. 
2. It is all depends on your javascript setup, ecosystem, framework, which programming patterns you use and etc. It is all up to you. 
For example in [this demo](https://github.com/VirgilSecurity/demo-firebase-js/blob/master/src/models/UserModel.ts), I use react for view and plain javascript for application model layer. I have `UserModel` which initialize E3kit on authentication flow and keep link to initialized e3kit instance. So UserModel is creates a ChatModel, which receives e3kit instance from it and uses it on different pages. There is no universal solution, it is only depends on your javascript knowledge and how your framework pass data between pages.

**Comment by yiytan92** [comment]
calling eThree.encrypt is taking about 2-4 seconds for the function to encrypt whatever message i pass in it. I was wondering if it takes just as long for you guys? Any tips to improve on the performance? My code currently initializes the EThree object function at every new chat window( since the recipient public keys are all different)

**Comment by xlwknx** [comment]
Encrypt and decrypt can take a while if you encrypt hundreds of kilobytes. For that case our [crypto library](https://github.com/VirgilSecurity/virgil-crypto-javascript) supports stream encryption. You can find examples here: https://github.com/VirgilSecurity/virgil-crypto-javascript/blob/master/examples/streams/node-streams.js or here for web: https://github.com/VirgilSecurity/virgil-crypto-javascript/tree/master/examples/file-upload
For now you can use virgil crypto directly by `eThreeInstance.virgilCrypto` link.
We are gonna wrap this functionality in E3kit in future release.

**Comment by xlwknx** [comment]
And could you provide me the code, which has that performance issues? 
Also, what size of the message and how many public keys are you use for encryption?

**Comment by yiytan92** [comment]
`    sendMessage = async () => {
        const { message } = this.state
        const eThree = this.state.eThree;
        const usersToEncryptTo = chat.users.filter(user => user !== user.username);
        const publicKeys = await eThree.lookupPublicKeys(usersToEncryptTo);
        const encryptedData = await eThree.encrypt(new ArrayBuffer(), publicKeys);
        const encryptedText = await eThree.encrypt(message, publicKeys);
        }
`

This is the code in my chat message component. For now, i'm only using 1 public key for 1-to-1 chat. Messages are very short strings like 'hi', for testing purposes as you can imagine. The encrypted text ends up looking something like this, if it helps: 
`'MIIC5AIBADCCAkIGCSqGSIb3DQEHA6CCAjMwggIvAgECMYICADCB/QIBAqAKBAgY+hiUq5UGwTAHBgMrZXAFAASB4jCB3wIBADAqMAUGAytlcAMhABZY9kzMwQ11KjuVXlfEiv1PMnzRgqiRASYd8cVIvJD+MBgGByiBjHECBQIwDQYJYIZIAWUDBAICBQAwQTANBglghkgBZQMEAgIFAAQwavg/RAlqgrnm2NRc8mul6f6pJwQqBTNFc2zP7jAO3N5HiCGJvJl7Kn0WDkW8FcbIMFEwHQYJYIZIAWUDBAEqBBDJYeJqYtXkYfVXm75FR30oBDDjIZ0M/VDutbx7Miux+7x/f9sYODH7fJOroooRFaSGw5zkGpd1VuMe5QAlQZo4LeYwgf0CAQKgCgQI3gzo1U/9WjMwBwYDK2VwBQAEgeIwgd8CAQAwKjAFBgMrZXADIQBpHmyRpTJGMhajGOKwQE0WjITtiJ3KlCncKgOE9WK3EDAYBgcogYxxAgUCMA0GCWCGSAFlAwQCAgUAMEEwDQYJYIZIAWUDBAICBQAEMEz6adnqwKD9XseuA6kNSiRLocy6Vc6tfbA3KKrKjEuQrin+s0j2RjvYK8kF8ed8yzBRMB0GCWCGSAFlAwQBKgQQ7bV+Rj0WxTXG30B7YkF6AgQw58vvsZvlbTAHU9ZaGtH5AATtDtRebdUq3bVXHPUVo7lrDGBOY/7A+3zlclMlDhPXMCYGCSqGSIb3DQEHATAZBglghkgBZQMEAS4EDLWeH+WjnDdQUSQyDKCBmDGBlTAjDBVWSVJHSUwtREFUQS1TSUdORVItSUSiCgQIGPoYlKuVBsEwbgwVVklSR0lMLURBVEEtU0lHTkFUVVJFolUEUzBRMA0GCWCGSAFlAwQCAwUABEABT9Sq1jV1XERfMC+kdALLyBMcbyp00nhPXmRn4OUt5IP3e8K7kWjA2Z2+l4L2lOr2BUvAXnosWiNlnFnMbrsEge1KSwdvFcB38lUDB3LoWBxDS5cN3g=='`

**Comment by xlwknx** [comment]
@yiytan92 
`const publicKeys = await eThree.lookupPublicKeys(usersToEncryptTo);`
This is network request to Virgil Cloud. It could take a time depends on your network connection speed. You could cache this keys, and perform this action separately from encryption. For example you can fetch user keys on chat windows open.
Encrypt for text message should work for `~130ms` average.
For large texts or files (over 500kb) you need to use `eThree.virgilCrypto.createStreamCipher` from examples above

**Comment by yiytan92** [comment]
@xlwknx I truly thank you for all the help you've provided me. I've tried improving the performance of eThree.decrypt but it's still taking about 3-4 seconds on average. I will keep investigating the issue. I'm quite satisfied that i've achieved end-to-end encryption and decryption on my app, but I was wondering, when I generate the Virgil JWT, is there a way to set it to not expire? Because I don't want to authenticate my users to regenerate the JWT every time.

**Comment by yiytan92** [comment]
I tried passing in 1 year in milliseconds: 
const generator = new JwtGenerator({
    appId: config.virgil.appId,
    apiKeyId: config.virgil.apiKeyId,
    apiKey: virgilCrypto.importPrivateKey(config.virgil.apiPrivateKey),
    accessTokenSigner: new VirgilAccessTokenSigner(virgilCrypto),
    millisecondsToLive: 31536000000 //1 year expiry
});

But I end up getting this error on my front-end:  [Unhandled promise rejection: VirgilHttpError: authorization token is invalid or contains invalid field(s)]

**Comment by vadimavdeev** [comment]
No, there's no way to generate a JWT that never expires and that's by design. JWTs are meant to be short-lived because there is no way to revoke them, i.e. once you issue a JWT for a user, it can be used to make authenticated requests on behalf of that user for as long as you set it to live and there is currently no way to stop the Virgil Cloud from accepting it. 

Imagine one of your JWTs becomes publicly accessible (e.g. accidentally published in a GitHub repo). Now anyone on the internet can use that token to make requests to the Virgil Cloud impersonating the user the token was generated for. So please make those tokens as short-lived as possible for your app. 

Btw, I'm not sure what you mean by "I don't want to authenticate my users to regenerate the JWT every time", but e3Kit will request a fresh token for you automatically when the current one expires.

**Comment by yiytan92** [comment]
@vadimavdeev For example, in my situation, my chat application is using eThree for message encryption. The default virgil Jwt expires in 20 minutes, so whenever I make calls to eThree after the 20 minutes, i get (VirgilHttpError: JWT is expired) because as you said the e3Kit will request a new refresh token.  Meaning every 20 minutes, I will have to call my endpoint to generate jwt token again? I've been trying to modify the input for millisecondsToLive in JwtGenerator, but I keep getting invalid error with that, could you show an example of using the JwtGenerator with a millisecond input which is more than 20 minutes? Much appreciated

**Comment by vadimavdeev** [comment]
Why is that a problem to call an endpoint once every 20 minutes? Don't you call other endpoints during the lifetime of you app? If so, how is calling a JWT endpoint different?

The Virgil Cloud will reject JWTs with more than 24 hours of lifetime. So you can't specify more than that.

That being said, I strongly suggest you make those tokes as short-lived as possible and call your endpoint to generate a new token once the current one expires.

**Comment by xlwknx** [comment]
@yiytan92 It means that you don't have private key on the device. If you call `cleanup` or clean your browser indexedDB storage, you deleting private key on device, so you need to download with `restorePrivateKey`. If you didn't `backupPrivateKey` you need to do it or don't delete private key from device. To obtain a new private key for identity which is registered you use `rotatePrivateKey`.
