### ISSUE TITLE
MultipleCardsError: "There are several public keys registered with identity, which is not supported

### ISSUE THREAD

**Issue by qualwebs** [VirgilSecurity/virgil-e3kit-js#25]
Before using **e3kit**, I was developing with core libraries of Virgil security but after a few days of setup I am continuously getting an error when I am calling,

	const encryptedMessage = virgilCrypto.signThenEncrypt(message, senderPrivateKey,receiverPublicKey);

> "Module: Virgil/crypto. Error code: 3. Argument given to a function is invalid. See function documentation."

Where it was working fine, I had completed all the steps to encrypt and decrypt. So now I have started looking at **e3kit**, but when I am calling

`await eThree.register();`

it is returning the error...

> "There are several public keys registered with identity, which is not supported"

Now is there any way to delete public keys related to identity. If any solution for the first issue it would be better.

**Comment by xlwknx** [comment]
Hi, @qualwebs 

I'm not sure why you receiving first error, my colleague @vadimavdeev will try to help you.

About e3kit error: it has programmatically restriction on client side to ensure that one user has only one card. But you can create multiple cards with Virgil SDK on Virgil Card Service. So you need to use e3kit only or keep one card for one identity. 
1. If you just have started develop the easiest option is to create a new application on a virgil-dashboard, so you'll have fresh environment without cards. 
2. If you already have a production application and active users, for now you can delete by REST API (and soon through Virgil SDK) https://developer.virgilsecurity.com/docs/api-reference/card-service/v5#delete-card-endpoint

**Comment by vadimavdeev** [comment]
@qualwebs It would be helpful to see the arguments you pass into the `signThenEncrypt` call and full error call stack as well. The `signThenEncrypt` function does a lot of things under the hood, so we need to know where exactly does it produce such error, because the error is too generic.

**Comment by qualwebs** [comment]
Thank you for the reply @vadimavdeev 
Here is the function to encrypt the message.
```
async signThenEncrypt(message) {
    const virgilCrypto = new VirgilCrypto();
    const keyStorage = new KeyStorage();
    const senderCards = await this.senderCardManager.searchCards(this.senderIdentity);
    const recipientCards = await this.recipientCardManager.searchCards(this.recipientIdentity);
    const senderPrivateKeyBytes = await keyStorage.load(this.senderIdentity);
    const senderPrivateKey = virgilCrypto.importPrivateKey(senderPrivateKeyBytes);
    const readers = senderCards.concat(recipientCards);
    if (senderPrivateKey === null) {
        console.log('Private key named ' + this.senderIdentity + ' does not exist');
        return;
    }

    if (recipientCards.length > 0) {
        const readersPublicKeys = readers.map(card => card.publicKey);
        const encryptedData = virgilCrypto.signThenEncrypt(
            message,
            senderPrivateKey,
            readersPublicKeys
        );

        return encryptedData.toString('base64');
    }

    throw new Error('Recipient cards not found');
}
```
In the function, I am receiving the card from Virgil for both sender and receivers so in future sender also will be able to see its messages, retrieving the private key of the sender from the local storage and passing all data to _signThenEncrypt_.
This is the error returned...
![screenshot_254](https://user-images.githubusercontent.com/13719000/55376568-98af6980-552e-11e9-9b93-308374986147.png)

**Comment by vadimavdeev** [comment]
@qualwebs Could you please log the `readersPublicKeys` array and paste the output here? Preferably as text. I'm interested in properties `identifier` and `key` of each public key, the following code does what I need:

```javascript
console.log(readersPublicKeys.map(({ identifier, key }) => `Identifier: ${identifier.toString('base64')}\nKey: ${key.toString('base64')}`).join('\n'))
```

**Comment by qualwebs** [comment]
Hello @vadimavdeev , this is the output returned by running the suggested code.
`Identifier: XFEf1UJ/quU= Key: MCowBQYDK2VwAyEA8cjoNG9fWoCxJKCMkEVxcHiuNWrReqldXprbNi9C8b8= Identifier: XFEf1UJ/quU= Key: MCowBQYDK2VwAyEA8cjoNG9fWoCxJKCMkEVxcHiuNWrReqldXprbNi9C8b8= Identifier: XFEf1UJ/quU= Key: MCowBQYDK2VwAyEA8cjoNG9fWoCxJKCMkEVxcHiuNWrReqldXprbNi9C8b8= Identifier: XFEf1UJ/quU= Key: MCowBQYDK2VwAyEA8cjoNG9fWoCxJKCMkEVxcHiuNWrReqldXprbNi9C8b8= Identifier: UXwf+PsoOwQ= Key: MCowBQYDK2VwAyEAnAyGj6OqhHUq0adNWgTnRdk9grqtHwHKcR8484aJXt8= Identifier: UXwf+PsoOwQ= Key: MCowBQYDK2VwAyEAnAyGj6OqhHUq0adNWgTnRdk9grqtHwHKcR8484aJXt8= Identifier: UXwf+PsoOwQ= Key: MCowBQYDK2VwAyEAnAyGj6OqhHUq0adNWgTnRdk9grqtHwHKcR8484aJXt8=`

**Comment by vadimavdeev** [comment]
The problem is that you have duplicate public keys - only two out of seven keys are unique. The keys identifiers must be unique for encryption to succeed. You need to figure out why you have duplicate public keys. There is no way you could have created multiple cards with the same identity AND public key.

**Comment by qualwebs** [comment]
Actually, I am working on a web messaging application where users can log in from different systems, so whenever user login it finds a key in local storage and if it is not available it creates new and publish.

About the same identity, I am sure, identity will be the same every time but the same public, maybe because I am using brain key with the same password every time.

If it is not the right way please suggest a better way to achieve this.

**Comment by vadimavdeev** [comment]
I was wrong, turns our you can create multiple cards with the same identity and public key, if their `created_at` instant is different. So, in your case you need to filter out the duplicate keys from the `readersPublicKeys` array before encrypting. Something like that:
```javascript
const readersPublicKeys = []; 
readers.map(card => card.publicKey).forEach(publicKey => {
    const isUnique = readersPublicKeys.every(k => k.identifier.equals(publicKey.identifier) === false);
    if (isUnique) {
        readersPublicKeys.push(publicKey);
    }
});
```

**Comment by qualwebs** [comment]
Hello, @vadimavdeev thanks for the snippet and yeah this has worked for me. But, I had to move to eThree due to some synchronization issue between mobile and web. Now I am facing another issue with it. The problem what I am facing is at last. I register the identity, backup & restore the keys, encrypt the message, etc. The issue is with decryption and only receiver side. I am getting the error

![screenshot_273](https://user-images.githubusercontent.com/13719000/56964585-150e8a00-6b79-11e9-926a-c26524e7f2de.png)

**Comment by xlwknx** [comment]
@qualwebs so you need tp specify correct sender public key in decrypt function to ensure that it was signed by sender.
