### ISSUE TITLE
Clarification on eThree.rotatePrivateKey()

### ISSUE THREAD

**Issue by parthya** [VirgilSecurity/virgil-e3kit-js#27]
We have a situation where we missed backing up privateKey before clearing from local. And not there is publicKey for the user, but no privateKey. 

Now, `EThree.rotatePrivateKey()` despite what the name suggests publishes new publicKey. 

Is there anyway we can create new privateKey or even `register()` again by clearing the publicKey?

**Comment by xlwknx** [comment]
Hi @parthya
`EThree.rotatePrivateKey()`is replacing old public key with new one. We keep one active public key for user in `E3kit`. But before you will `rotatePrivateKey`, the old public key will be active, so users can encrypt data for wrong public key. For this situation we have HTTP endpoint, which delete active  public key: https://developer.virgilsecurity.com/docs/api-reference/card-service/v5#delete-card-endpoint
(Public Key stored in Virgil Card, you can read more here: https://developer.virgilsecurity.com/docs/glossary#virgil-card)

After old card is delete you can call `register()` again.

Soon we will implement card deletion in E3kit and Virgil SDK.

**Comment by xlwknx** [comment]
Hi @parthya
`EThree.rotatePrivateKey()` is replacing old public key with new one. We keep one active public key for user in E3kit. But before you will `rotatePrivateKey`, the old public key will be active, so users can encrypt data for wrong public key. For this situation we have HTTP endpoint, which delete active public key: https://developer.virgilsecurity.com/docs/api-reference/card-service/v5#delete-card-endpoint
(Public Key stored in Virgil Card, you can read more here: https://developer.virgilsecurity.com/docs/glossary#virgil-card)

After old card is delete you can call `register()` again.

Soon we will implement card deletion in E3kit and Virgil SDK.

But I think is a better way do not let users to delete private key before it was backed up. There is no way track it by `E3kit` but you can flag users who backed up private key in your database and clean keys only for that kind of users.

Was this information helpful to you?

**Comment by parthya** [comment]
Thanks @xlwknx , certainly helpful. I will try deletion and confirm.

> But I think is a better way do not let users to delete private key before it was backed up.

Of course, this is in development phase, when backing up wasn't done.

**Comment by xlwknx** [comment]
I'm closing issue for now, but if you will have other questions, feel free to open it and write questions here.

**Comment by parthya** [comment]
@xlwknx Tried https://developer.virgilsecurity.com/docs/api-reference/card-service/v5#search-cards-endpoint to find the card (get `content_snapshot` & `signatures`) for a particular `identity` but get 404 error.

**Comment by xlwknx** [comment]
@parthya Could you please provide logs?

**Comment by xlwknx** [comment]
@parthya Hope you solve your problem. 
If you will need any further help, feel free to write your questions.

**Comment by parthya** [comment]
@xlwknx sorry for not replying earlier.

We resolved the issue, well, by using different identity-key itself. So there was no need to delete those publicKeys (the ones without any private key backup). 

Maybe having these rare admin features on the dashboard, could be a easier solution.

**Comment by xlwknx** [comment]
@parthya hi, yes we will implement this functionality in our dashboard. But for now you can create new application in development phase and it will has no cards. Or just delete them.
