### ISSUE TITLE
Improve error message on restorePrivateKey (entry doesn't exist)

### ISSUE THREAD

**Issue by cardoso** [VirgilSecurity/virgil-e3kit-js#63]
<img width="594" alt="Screen Shot 2019-10-12 at 4 21 02 PM" src="https://user-images.githubusercontent.com/5606812/66706745-2b666780-ed0d-11e9-9b56-d27b214abd8d.png">

"undefined is not an object" I think this is a bug when generating the error, but anyway:

I think this should be wrapped with PrivateKeyBackupNotFound() or something similar.

Version used: E3Kit JS 0.6.0 (On RN, but probably web as well)

**Comment by snanovskyi** [comment]
Actually we have [PrivateKeyNoBackupError](https://github.com/VirgilSecurity/virgil-e3kit-js/blob/master/src/errors.ts#L70) 🙂
This error is specific to React Native. It should be fixed in the new release.
