### ISSUE TITLE
.AsyncStorageStatic is not assignable to type

### ISSUE THREAD

**Issue by rantwijk** [VirgilSecurity/virgil-e3kit-js#82]
**Describe the bug**
Version: `"@virgilsecurity/e3kit": "^0.7.0-beta.2"`
Import: `import { EThree } from '@virgilsecurity/e3kit-native';`
After following the installation steps, a type error is shown related to AsyncStorage. When using AsyncStorage from react-native (deprecated), this error does not appear.

**To Reproduce**
1. Follow Virgil E3Kit SDK for React Native installation instructions.
2. Try to use the example Usage code to initialize EThree using TypeScript.
3. "EThree.initialize(getToken, { AsyncStorage })" will show a Type error.

**Expected behavior**
No error.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Browser Chrome
 - Version 78

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max Simulator
 - OS: 13.0
 - Browser Safari

**Additional context**
Error:
`(property) EThreeNativeInitializeOptions.AsyncStorage: AsyncStorageStatic`

`Type 'import("@react-native-community/async-storage").AsyncStorageStatic' is not assignable to type 'import("/Users/x/x/x/x/mobile-app/node_modules/@virgilsecurity/e3kit-native/node_modules/@types/react-native/index").AsyncStorageStatic'.
  Types of property 'multiGet' are incompatible.
    Type '(keys: string[], callback?: ((errors?: Error[] | undefined, result?: [string, string | null][] | undefined) => void) | undefined) => Promise<[string, string | null][]>' is not assignable to type '(keys: string[], callback?: ((errors?: Error[] | undefined, result?: [string, string][] | undefined) => void) | undefined) => Promise<[string, string][]>'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'result' and 'result' are incompatible.
          Type '[string, string | null][] | undefined' is not assignable to type '[string, string][] | undefined'.
            Type '[string, string | null][]' is not assignable to type '[string, string][]'.
              Type '[string, string | null]' is not assignable to type '[string, string]'.
                Type 'string | null' is not assignable to type 'string'.
                  Type 'null' is not assignable to type 'string'.ts(2322)`

`EThree.d.ts(5, 5): The expected type comes from property 'AsyncStorage' which is declared here on type 'EThreeNativeInitializeOptions'`

**Comment by snanovskyi** [comment]
Hi @rantwijk !
It appears that typings for [@react-native-community/async-storage](https://github.com/react-native-community/async-storage/blob/LEGACY/types/index.d.ts#L54) and [react-native](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L6841) are different 😔
We will get back to you as soon as we will fix it.
For now, you can cast your storage to other type or use `// @ts-disable` comment.

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/75348395-179b5680-58e6-11ea-8b04-200a4060c709.png)

Same here!

**Comment by hyochan** [comment]
This even fails the testing build since the `AsyncStorage` is different. 
https://circleci.com/gh/dooboolab/hackatalk-mobile/504?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by azirb** [comment]
Closing as outdated

**Comment by nzcodarnoc** [comment]
Still the same type bug for me with the following versions:
`    "@storybook/react-native": "6.0.1-beta.7"`
`    "@react-native-async-storage/async-storage": "^1.17.10",`
